### ISSUE TITLE
ERR:  [Error: Pin has not been exported]

### ISSUE THREAD

**Issue by maavuz** [bnielsen1965/rpi-gpio-buttons#1]
Hey, i am getting this error "ERR:  [Error: Pin has not been exported]". any solutions?

**Comment by bnielsen1965** [comment]
Can you add some details about the hardware you are using and if possible include your code that is setting up the buttons?

This error has a number of possible causes, the rpi-gpio repo has some discussions about the issue that may help, i.e. here...
https://github.com/JamesBarwell/rpi-gpio.js/issues/38

**Comment by shivag12** [comment]
Having the same issue : 

Code : 
var buttons = require('rpi-gpio-buttons')([17]);

buttons.on('pressed', function (pin) {
  console.log('User pressed button on pin ', pin);
});

Hardware : 
Raspberry PI 3 Model B
Node V8.6.0

**Comment by bnielsen1965** [comment]
@shivag12 were you trying to use GPIO17? Try...
`var buttons = require('rpi-gpio-buttons')([11]);
`
The pin number is the header pin number and the header pin number for GPIO17 is 11.

Header pin 17 is a 3.3V power pin which may explain the failure to export.

I'll test this on a fresh Pi 3 setup here.

**Comment by bnielsen1965** [comment]
@shivag12 @maavuz 
Tested and confirmed, if I try **require('rpi-gpio-buttons')([17])** I get an error saying the pin is not exported.
If I try **require('rpi-gpio-buttons')([11])** then it works.

I may need to add a note to the documentation to make it clear that the pin number is the header pin number. I.E. GPIO17 = Header Pin 11.

For the Pi 3 you can refer to this page to see the GPIO numbers and the header pin numbers...

https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md

**Comment by shivag12** [comment]
Thanks @bnielsen1965 , It works now.. !!

**Comment by bnielsen1965** [comment]
I added a note in the README.md to help clarify that pin numbers are the header pin number from the printed circuit board.

@maavuz I am assuming this also addresses your issue, if not then let me know and I'll see if I can help determine the cause.

**Comment by maavuz** [comment]
@bnielsen1965 Yes i got it sorted out. i also made a few changes in source code to get this working. i will create a pull request later as i am still working on it and it will help other people too.
