### ISSUE TITLE
install fails on node v10 due to old dependency

### ISSUE THREAD

**Issue by bradanlane** [bnielsen1965/rpi-gpio-buttons#4]
the package.json has dependency for rpi-gpio 0.9.1 which has a dependency on an old epoll which uses a deprecated class member. 

epoll has been updated and then rpi-gpio has been updated.

rpi-gpio-buttons will not install unless the package dependency is update

**Comment by bradanlane** [comment]
I forked the repository and made the necessary change. Feel free to copy my edits.

**Comment by bnielsen1965** [comment]
Have you tested the changes on older versions of node?

I'll clone your repo and do some testing here.

**Comment by bnielsen1965** [comment]
I tested your repo changes on node v4, v6, v8, and v10, seems to be good everywhere.

Do you want to do a pull request, then I'll publish to npm?

**Comment by bradanlane** [comment]
No problem. I’ll submit the pull request. 

Thanks for testing the changes.

**Comment by bnielsen1965** [comment]
merged pull request and npm published as 1.1.1. thanks @bradanlane
