### ISSUE TITLE
Event detection without gpio functionality

### ISSUE THREAD

**Issue by bartbutenaers** [bnielsen1965/rpi-gpio-buttons#8]
Hi Bryan (@bnielsen1965),

This is a very nice library!
I would like to integrate it into the open-source Node-RED IOT dataflow framework, however I have a problem doing that.

Node-RED is a data flow, consisting out of nodes that run independently of each other (and which send messages to each other).   A flow to read a physical button via a gpio pin could look like this:

![image](https://user-images.githubusercontent.com/14224149/94375571-e81b2980-0114-11eb-8199-c525ad08fb7a.png)

The first (already existing) _gpio_ node will listen to a specified gpio pin, and send - every time the gpio pin value changes - messages (containing a 0 or 1) to a next node.  In this case the second node would be my (new) _button-events_ node (based on your library), which would detect single click/double click/long press ... (based on the timings between the input messages from the gpio node).  And my _button-events_ node would send output messages (containing 'double click', 'long press'...) to the next nodes in the flow.

But this means that ***I need your event detection without the gpio stuff***, because there is already a gpio node in Node-RED.  So I'm wondering if the event detection could e.g. be made available as a separate xxx npm library.  Then your rpi-gpio-buttons library could use that xxx library as a ***dependency*** (and add the gpio functionality).  

I mean an xxx library that has following functionality:
+ It is possible at the start to specify the idle and active values (e.g. 0 and 1).
+ It is possible to feed input values.
+ It is possible to stop it (so the timer is stopped).
+ It will generate events based on the input data.

I hope that you understand why I need this, and hope you like the idea ...  
Thanks a lot!

Bart

**Comment by bnielsen1965** [comment]
Hi Bart,

Very feasible, is there some documentation that would describe the messaging format I would need to use for the listener and the emitter?

Bryan

EDIT: I setup a Raspberry Pi with node-red and figured out what I think is needed to support the messaging/payload processing in a node. Here is the github repo with the event process minus all the rpi-gpio stuff...

https://github.com/bnielsen1965/button-events

**Comment by bartbutenaers** [comment]
Morning Bryan,
That is truly amazing.  What a support ...
At first sight that seems indeed to be exactly what I need.
Will experiment with it tonight.  Now off to work.  
Seems there is some time difference between the both of us ;-)
Greetings from Belgium,
Bart

**Comment by bartbutenaers** [comment]
Hi Bryan,
Nice work!! 
At first sight it seems to be working smooth:

![button_events_flow](https://user-images.githubusercontent.com/14224149/94484199-50810e00-01dc-11eb-9b6e-6be35d1bfbdf.gif)

In this flow I'm injecting 0's and 1's manually (i.e. software buttons).  My colleague has all kind of home automation hardware running, so he will test various hardware setups.  Will keep you updated...

One question.  When a flow is changed and deployed (to the server), then Node-RED triggers a `close` event where I need to ***cleanup*** all kind of resources.  One of the common things to do is cleanup of all running timers, to make sure there are no parallel running timers when the flow is started again.   Currently I do it like this:
```
node.on("close",function() { 
   if (node.buttonEvents.emitTimer) {
       clearTimeout(node.buttonEvents.emitTimer);
       node.buttonEvents.emitTimer = null;
   }
});
```

That works but I don't like to call internal stuff from your library, since that might fail in a future version of your lib.  So therefore it would be nice if you could add a function (`stop`, `dispose`, `cleanup`...) that does all the required cleanup, like e.g. stopping the timer.  Then I could simply do this:
```
node.on("close",function() { 
   node.buttonEvents.cleanup();
});
```
Of course this will only be a problem when the user enters a longer interval, but just to make sure ...

Bart

**Comment by bnielsen1965** [comment]
Added cleanup() method.

When called it will disable actions on gpioChange() calls, removes event listeners, and clears debounce and emit timers. 

EDIT: Once it all looks good I'll publish to npm.

**Comment by bartbutenaers** [comment]
Faster than my shadow ...
And seems my cleanup version was incomplete, so I really appreciate that you have added a `cleanup` function!
For me this issue is indeed completely finished, so you can publish it on NPM.
When my colleague should have an issue somehow with the events on his hardware, then I will create a new issue.

BTW your name is now immortalized on my [readme](https://github.com/bartbutenaers/node-red-contrib-button-events#node-red-contrib-button-events) page.  A little advertisement cannot harm :-)

Was nice doing business with you!
Kind regards,
Bart

**Comment by bnielsen1965** [comment]
Published...

https://www.npmjs.com/package/button-events

Thanks for the attribution. ;)
