### ISSUE TITLE
Include method to passthrough destroy() to rpi_gpio

### ISSUE THREAD

**Issue by raintonr** [bnielsen1965/rpi-gpio-buttons#9]
In rpi-gpio module there is a destroy() method to tear down any previously set up channels. Should be run when your program stops, or needs to reset the state of the pins.

rpi-gpio-buttons needs a similar method.

On this topic, it might also be nice if one could pass an existing rpi-gpio instance in options for cases where a caller wants to set that up themselves and only debounce a limited number of ports.

**Comment by bnielsen1965** [comment]
I can add a destroy() method and option to pass an existing rpi-gpio instance.

> and only debounce a limited number of ports.

**Can you go into a bit more detail on this? Are you thinking you want to have external control of the debounce?**

I had plans to rework this module and implement the new [button-events](https://www.npmjs.com/package/button-events) module which pulls the event logic into a separate module. The button-events module allows you to disable the debounce feature by setting the timing to 0, however, this disables the debounce for all incoming signals.

**Last question, if I rework this module into a new ES6 class, which would change how an instance of rpi-gpio-buttons is created, is that going to cause issues in the way you are using the module?**

**Comment by bnielsen1965** [comment]
I just added a new branch, [2dot0](https://github.com/bnielsen1965/rpi-gpio-buttons/tree/2dot0) which has all the aforementioned changes. But I haven't updated the documentation yet.

Note in the [testing example](https://github.com/bnielsen1965/rpi-gpio-buttons/blob/2dot0/test/index.js#L7) that the array of pins is included as part of the configuration settings when creating a new instance of rpi-gpio-buttons.

This new class also requires that you call an init() method to initialize the instance after it is created and the method is asynchronous. At the bottom of the test.js script you can see where the init() is called.

The new [init() method](https://github.com/bnielsen1965/rpi-gpio-buttons/blob/2dot0/index.js#L25) will accept an pre-setup rpi-gpio as an argument, so you can setup your own rpi-gpio and pass it into the rpi-gpio-buttons init() method.

And the class also has a destroy method that will call the rpi-gpio.destroy(). I just realized that I missed some additional cleanup in the destroy() method, the button-events module I'm using has a cleanup method that I should be calling, more work to do...

**Comment by raintonr** [comment]
> I can add a destroy() method and option to pass an existing rpi-gpio instance.

Cool

> > and only debounce a limited number of ports.
> 
> **Can you go into a bit more detail on this? Are you thinking you want to have external control of the debounce?**

Sorry, I mean have buttons on a limited number of ports while using others for general I/O. Eg. you want to use 4 ports on your RPi. 1 in, 1 out and 2 input buttons. You setup rpi-gpio in your own code with the 1 in and 1 out but then initiate rpi-gpio-buttons passing the port numbers of the 2 buttons.

FWIW, in this scenario (I have something like this now) have to do 'debounce' (ie. wait for the general input port to stabilise before acting on that change) in my own code. And that's cool - the input I'm talking about is a door sensor so don't think I should expect to be able to use that as a button as it's state changed infrequently.

> **Last question, if I rework this module into a new ES6 class, which would change how an instance of rpi-gpio-buttons is created, is that going to cause issues in the way you are using the module?**

Probably, but don't worry - I'll update my code. What about everyone else though? ;)

**Comment by bnielsen1965** [comment]
> Probably, but don't worry - I'll update my code. What about everyone else though? ;)

When I publish this branch I'll up the version number to 2.0.0 since it will be a breaking change. This should protect any applications that are using a ^1.x.x dependency.

The [README.md](https://github.com/bnielsen1965/rpi-gpio-buttons/tree/2dot0#raspberry-pi-gpio-button-event-emitter) is complete and I've documented the gpio option in the init() method along with the other changes.

I'll publish this to npm after I've done a bit more testing. Let me know if you see any issues.

You may already know this, but just in case, you can install the development branch as and dependency like this...

npm install --save bnielsen1965/rpi-gpio-buttons#2dot0

**Comment by raintonr** [comment]
Nice. Thx.

This can work in my scenario, but quick question: is there any reason you decided to leave the setup of pins (direction, edge) to the caller when an `rpi-gpio` instance is passed? I mean, is there some reason this can't be done by `rpi-gpio-buttons` when the pins and `rpi-gpio` instance is passed in the constructor? Maybe I'm missing something but this seems inefficient for the caller.

**Comment by bnielsen1965** [comment]
> is there any reason you decided to leave the setup of pins (direction, edge) to the caller when an rpi-gpio instance is passed?

That was my interpretation of your request. I was under the assumption that rpi-gpio was already configured and GPIOs setup by the application. I may have read too much into your request, it's not published yet so lets work through this...

**So the main objective is to call require('rpi-gpio') once and ensure the main application and rpi-gpio-buttons are both using the same instance of rpi-gpio?**

If gpio is passed in the constructor options then I would not call require('rpi-gpio') and I would skip the setMode().

**And rpi-gpio-buttons should always setup the button GPIO pins itself?**

There would be no way to override the GPIO setup for the button pins, perhaps this makes sense because the button event logic is dependent on a proper GPIO setup.

**Comment by raintonr** [comment]
> That was my interpretation of your request.

Oops... sorry for not being clearer.

> **So the main objective is to call require('rpi-gpio') once and ensure the main application and rpi-gpio-buttons are both using the same instance of rpi-gpio?**

Yes.

> If gpio is passed in the constructor options then I would not call require('rpi-gpio') and I would skip the setMode().

Sounds good.

> **And rpi-gpio-buttons should always setup the button GPIO pins itself?**

That was what I was hoping for.

 > There would be no way to override the GPIO setup for the button pins, perhaps this makes sense because the button event logic is dependent on a proper GPIO setup.

That sounds reasonable too.

**Comment by bnielsen1965** [comment]
Ready for another review.

An existing rpi-gpio instance is now passed as gpio in the constructor configuration. No arguments for the init() call.

The button GPIO pins are always configured during init() even if an existing rpi-gpio is passed in the constructor configuration options.

Also updated the README to match the changes.

**Comment by raintonr** [comment]
This all looks good to me. Thanks! :+1:

Will you be making a release soon or waiting for more testing/feedback?

**Comment by bnielsen1965** [comment]
I'm going to do a bit of testing tonight and if I don't run into any issues I'll publish tonight.

**Comment by bnielsen1965** [comment]
Merged and published. Thanks for working with me on the update.

**Comment by raintonr** [comment]
Excellent. Thank you :+1:

**Comment by raintonr** [comment]
Ah... there is one thing... I notice in the `destroy` method `this.gpio.destroy` is being called.

To begin with, that was what this issue was about, but since you have implemented the ability to pass in an already existing `rpi-gpio` object... ah... one should not destroy what one did not create should they?

So sorry I missed this, but think the module needs to make a note of if the `rpi-gpio` was passed in, and if so, do not destroy it and leave that the the original creator (the caller).

**Comment by bnielsen1965** [comment]
Easy fix, but as I stare are the destroy() method I'm starting to think that it should also be an async method because the rpi-gpio destroy() is async.

I'll make the changes and publish...

**Comment by bnielsen1965** [comment]
Done, published as v2.0.1.

The destroy() method now keeps gpio intact if it was passed in the constructor. I also added the missing documentation for the destroy() method.

**Comment by raintonr** [comment]
Nice. Thx.
